name: Tests
on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Run unit tests
        run: yarn test
